# =========================================================
# Supplementary material
# Script 02: Figure 8 - sensitivity analysis plot
# =========================================================
# This script creates a line plot showing the combined share of Natura 2000
# area in the High and Critical exposure classes across depth-threshold and
# weighting scenarios for winter and summer.
#
# Required input:
# outputs/tables/fixed_classification_summary.csv
# generated by scripts/01_exposure_index_and_tables.R
# =========================================================

# ---- Packages ----
required_packages <- c("dplyr", "tidyr", "stringr", "readr", "ggplot2")
missing_packages <- required_packages[!required_packages %in% rownames(installed.packages())]
if (length(missing_packages) > 0) {
  install.packages(missing_packages)
}

library(dplyr)
library(tidyr)
library(stringr)
library(readr)
library(ggplot2)

# ---- Font ----
font_family <- "Times New Roman"

# ---- Paths ----
table_file <- "outputs/tables/fixed_classification_summary.csv"
figure_dir <- "outputs/figures"
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

if (!file.exists(table_file)) {
  stop("Required table not found: ", table_file, ". Run scripts/01_exposure_index_and_tables.R first.")
}

# ---- Load fixed-threshold classification summary ----
fixed_summary <- read_csv(table_file, show_col_types = FALSE)

required_columns <- c(
  "season", "depth_thresholds_m", "weighting_scenario",
  "exposure_class", "natura_area_percent"
)
missing_columns <- setdiff(required_columns, names(fixed_summary))
if (length(missing_columns) > 0) {
  stop("Missing columns in ", table_file, ": ", paste(missing_columns, collapse = ", "))
}

# ---- Prepare data for plotting ----
threshold_order <- c("10/50", "20/50", "20/60")
scenario_order <- c("30_70", "50_50", "70_30")
season_order <- c("winter", "summer")

plot_data <- fixed_summary %>%
  filter(exposure_class %in% c("High", "Critical")) %>%
  group_by(season, depth_thresholds_m, weighting_scenario) %>%
  summarise(
    high_critical_percent = sum(natura_area_percent, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  complete(
    season = season_order,
    depth_thresholds_m = threshold_order,
    weighting_scenario = scenario_order,
    fill = list(high_critical_percent = 0)
  ) %>%
  mutate(
    season = factor(season, levels = season_order),
    depth_thresholds_m = factor(depth_thresholds_m, levels = threshold_order),
    weighting_scenario = factor(weighting_scenario, levels = scenario_order),
    weighting_label = str_replace(as.character(weighting_scenario), "_", "/"),
    x_label = paste0(as.character(depth_thresholds_m), "\n", weighting_label)
  )

x_order <- expand.grid(
  depth_thresholds_m = threshold_order,
  weighting_scenario = scenario_order,
  stringsAsFactors = FALSE
) %>%
  mutate(
    weighting_label = str_replace(weighting_scenario, "_", "/"),
    x_label = paste0(depth_thresholds_m, "\n", weighting_label)
  ) %>%
  pull(x_label)

plot_data <- plot_data %>%
  mutate(x_label = factor(x_label, levels = x_order))

# ---- Plot ----
y_min <- max(0, min(plot_data$high_critical_percent, na.rm = TRUE) - 5)
y_max <- max(plot_data$high_critical_percent, na.rm = TRUE) + 5

p_figure_08 <- ggplot(
  plot_data,
  aes(x = x_label, y = high_critical_percent, group = season, color = season)
) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 2.5) +
  scale_color_manual(
    name = "Season",
    values = c("winter" = "#F8766D", "summer" = "#00BFC4"),
    labels = c("Winter", "Summer")
  ) +
  coord_cartesian(ylim = c(y_min, y_max)) +
  labs(
    x = "Depth thresholds (m) and weighting scenario",
    y = "High + Critical Natura 2000 area (%)"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    text = element_text(family = font_family),
axis.line = element_line(size = 0.5),
    axis.text.x = element_text(size = 10),
    panel.grid.minor = element_blank(),
    legend.position = "right"
  )

print(p_figure_08)

# ---- Export ----
output_tiff <- file.path(figure_dir, "Figure_08_sensitivity_analysis.tiff")
output_png <- file.path(figure_dir, "Figure_08_sensitivity_analysis.png")

ggsave(output_tiff, p_figure_08, width = 16, height = 10, units = "cm", dpi = 600, compression = "lzw")
ggsave(output_png, p_figure_08, width = 16, height = 10, units = "cm", dpi = 600)

message("Figure exported to: ", output_tiff)
message("Preview exported to: ", output_png)
