# =========================================================
# Supplementary material
# Script 04: Figure 10 - quartile-based exposure classes
# =========================================================
# This script creates a stacked bar chart showing the seasonal
# distribution of Natura 2000 area across quartile-based exposure
# classes for the 50/50 weighting scenario and 20/60 m
# depth-threshold setting.
#
# Required input:
# outputs/tables/quantile_classification_summary.csv
#
# Generated by:
# scripts/01_exposure_index_and_tables.R
#
# Outputs:
# outputs/figures/Figure_10_quartile_exposure_classes.tiff
# outputs/figures/Figure_10_quartile_exposure_classes.png
# =========================================================


# ---------------------------------------------------------
# Packages
# ---------------------------------------------------------

required_packages <- c(
  "dplyr",
  "readr",
  "ggplot2",
  "ragg",
  "systemfonts"
)

missing_packages <- required_packages[
  !required_packages %in% rownames(installed.packages())
]

if (length(missing_packages) > 0) {
  install.packages(missing_packages)
}

library(dplyr)
library(readr)
library(ggplot2)


# ---------------------------------------------------------
# Font
# ---------------------------------------------------------

font_family <- "Times New Roman"

# Check whether Times New Roman is available on the system
available_fonts <- systemfonts::system_fonts()

if (!font_family %in% available_fonts$family) {
  warning(
    "Times New Roman was not found on this system. ",
    "The graphics device may substitute another serif font."
  )
}


# ---------------------------------------------------------
# Paths
# ---------------------------------------------------------

table_file <- "outputs/tables/quantile_classification_summary.csv"

figure_dir <- "outputs/figures"

dir.create(
  figure_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

if (!file.exists(table_file)) {
  stop(
    "Required table not found: ",
    table_file,
    ". Run scripts/01_exposure_index_and_tables.R first."
  )
}


# ---------------------------------------------------------
# Load data
# ---------------------------------------------------------

quantile_summary <- read_csv(
  table_file,
  show_col_types = FALSE
)


# ---------------------------------------------------------
# Check required columns
# ---------------------------------------------------------

required_columns <- c(
  "season",
  "depth_thresholds_m",
  "weighting_scenario",
  "exposure_class",
  "natura_area_percent"
)

missing_columns <- setdiff(
  required_columns,
  names(quantile_summary)
)

if (length(missing_columns) > 0) {
  stop(
    "Missing columns in ",
    table_file,
    ": ",
    paste(missing_columns, collapse = ", ")
  )
}


# ---------------------------------------------------------
# Data preparation
# ---------------------------------------------------------

class_order <- c(
  "No exposure",
  "Low",
  "Moderate",
  "High",
  "Critical"
)

plot_data <- quantile_summary %>%
  
  filter(
    depth_thresholds_m == "20/60",
    weighting_scenario == "50_50"
  ) %>%
  
  mutate(
    
    # Seasonal order
    season = factor(
      season,
      levels = c("winter", "summer")
    ),
    
    # Exposure-class order
    exposure_class = factor(
      exposure_class,
      levels = class_order
    ),
    
    # Numerical x-position for each row
    xpos = ifelse(
      season == "winter",
      1,
      2
    )
  ) %>%
  
  arrange(
    season,
    exposure_class
  )


# ---------------------------------------------------------
# Check data used in Figure 10
# ---------------------------------------------------------

if (nrow(plot_data) == 0) {
  stop(
    "No rows found for depth_thresholds_m = '20/60' ",
    "and weighting_scenario = '50_50'."
  )
}

print(plot_data)


# ---------------------------------------------------------
# Figure
# ---------------------------------------------------------

p_figure_10 <- ggplot(
  plot_data,
  aes(
    x = xpos,
    y = natura_area_percent,
    fill = exposure_class
  )
) +
  
  # Stacked bars
  geom_col(
    width = 0.50,
    color = "black",
    linewidth = 0.25,
    position = position_stack(
      reverse = TRUE
    )
  ) +
  
  # Percentage labels to the right of each bar
  geom_text(
    aes(
      x = xpos + 0.32,
      label = ifelse(
        natura_area_percent >= 0.01,
        paste0(
          round(natura_area_percent, 1),
          "%"
        ),
        ""
      )
    ),
    position = position_stack(
      vjust = 0.5,
      reverse = TRUE
    ),
    hjust = 0,
    size = 4.55,
    family = font_family
  ) +
  
  # Winter / Summer labels
  scale_x_continuous(
    breaks = c(1, 2),
    labels = c(
      "Winter",
      "Summer"
    )
  ) +
  
  # Exposure-class colours
  scale_fill_manual(
    name = "Exposure class",
    values = c(
      "No exposure" = "darkblue",
      "Low" = "gold",
      "Moderate" = "forestgreen",
      "High" = "red",
      "Critical" = "red4"
    ),
    breaks = class_order,
    drop = FALSE
  ) +
  
  # Plot limits
  coord_cartesian(
    ylim = c(0, 100),
    xlim = c(0.5, 2.8),
    clip = "off"
  ) +
  
  # Axis labels
  labs(
    x = NULL,
    y = "Share of Natura 2000 area (%)"
  ) +
  
  # Theme
  theme_classic(
    base_size = 13,
    base_family = font_family
  ) +
  
  theme(
    
    text = element_text(
      family = font_family
    ),
    
    axis.title = element_text(
      family = font_family,
      size = 12
    ),
    
    axis.text = element_text(
      family = font_family,
      size = 12
    ),
    
    legend.title = element_text(
      family = font_family,
      size = 12
    ),
    
    legend.text = element_text(
      family = font_family,
      size = 11
    ),
    
    legend.position = "bottom",
    
    plot.margin = margin(
      10,
      50,
      10,
      10
    )
  )


# ---------------------------------------------------------
# Display figure in RStudio
# ---------------------------------------------------------

print(p_figure_10)


# ---------------------------------------------------------
# Export paths
# ---------------------------------------------------------

output_tiff <- file.path(
  figure_dir,
  "Figure_10_quartile_exposure_classes.tiff"
)

output_png <- file.path(
  figure_dir,
  "Figure_10_quartile_exposure_classes.png"
)


# ---------------------------------------------------------
# Export TIFF
# ---------------------------------------------------------
# ragg renders the specified system font directly into
# the raster image, avoiding the Times -> sans-serif
# substitution that can occur with some default devices.

ggsave(
  filename = output_tiff,
  plot = p_figure_10,
  device = ragg::agg_tiff,
  width = 15,
  height = 10,
  units = "cm",
  dpi = 600,
  compression = "lzw",
  background = "white"
)


# ---------------------------------------------------------
# Export PNG preview
# ---------------------------------------------------------

ggsave(
  filename = output_png,
  plot = p_figure_10,
  device = ragg::agg_png,
  width = 15,
  height = 10,
  units = "cm",
  dpi = 300,
  background = "white"
)


# ---------------------------------------------------------
# Messages
# ---------------------------------------------------------

message(
  "TIFF figure exported to: ",
  output_tiff
)

message(
  "PNG preview exported to: ",
  output_png
)

message(
  "Font used for export: ",
  font_family
)